apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.vaultUrl | quote }}
      tenantId: {{ .Values.tenantId | quote }}
