global:
  commonLabels:
    estabilis.io/managed-by: platform
    estabilis.io/component: cert-manager

installCRDs: true

replicaCount: 1

serviceAccount:
  create: true

prometheus:
  enabled: true
  servicemonitor:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi

webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

cainjector:
  replicaCount: 1
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 256Mi
