global:
  commonLabels:
    estabilis.io/managed-by: platform
    estabilis.io/component: cert-manager

installCRDs: true

replicaCount: 1

serviceAccount:
  create: true

prometheus:
  enabled: true
  servicemonitor:
    enabled: false

webhook:
  replicaCount: 1

cainjector:
  replicaCount: 1
