# Trivy Operator — continuous vulnerability scanning in-cluster
# https://github.com/aquasecurity/trivy-operator

commonLabels:
  estabilis.io/managed-by: platform
  estabilis.io/component: trivy-operator

trivy:
  ignoreUnfixed: true

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi

operator:
  scanJobsConcurrentLimit: 1
  vulnerabilityScannerEnabled: true
  configAuditScannerEnabled: true
  rbacAssessmentScannerEnabled: true
  infraAssessmentScannerEnabled: false

trivyOperator:
  scanJobPodTemplatePodSecurityContext:
    runAsNonRoot: false
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: false

tolerations:
  - key: "estabilis.io/workload-type"
    operator: "Equal"
    value: "platform"
    effect: "NoSchedule"
