apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: grafana-db
  namespace: cnpg-system
  {{- include "estabilis.metadata" . | nindent 2 }}
spec:
  name: grafana
  owner: grafana
  cluster:
    name: {{ .Values.cnpgClusterName }}
