{
 "title": "Kubernetes/Tanzu/Velero",
 "description": "Velero Stats maintained by Velero team",
 "tags": [ "velero" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total, schedule)"
    }
   },
   {
    "name": "csi_backup_name",
    "query": {
     "query": "label_values(velero_csi_snapshot_attempt_total, backupName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backup", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Backup Total",
   "type": "stat",
   "description": "The sum of one-off backup and schedule backup success total ",
   "gridPos": { "x": 0, "y": 1, "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_backup_total" }
   ]
  },
  {
   "title": "Backup Last Status",
   "type": "stat",
   "description": "The last status of the backup. A value of 1 indicates success, while a value of 0 indicates failure.",
   "gridPos": { "x": 3, "y": 1, "w": 3, "h": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_last_status{schedule!=\"\"}",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup Storage Status",
   "type": "stat",
   "gridPos": { "x": 6, "y": 1, "w": 3, "h": 5 },
   "targets": [
    {
     "expr": "velero_backup_location_status_gauge",
     "legendFormat": "{{ backup_location_name }}"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "gridPos": { "x": 9, "y": 1, "w": 5, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum(increase(velero_backup_success_total{schedule!=\"\"}[24h])) / clamp_min(sum(increase(velero_backup_attempt_total{schedule!=\"\"}[24h])), 1), 1)"
    }
   ]
  },
  {
   "title": "Volume snapshot Success Rate",
   "type": "gauge",
   "gridPos": { "x": 14, "y": 1, "w": 5, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(velero_backup_last_status{schedule!=\"\"} == bool 1)"
    }
   ]
  },
  {
   "title": "Backup Deletion Success Rate",
   "type": "gauge",
   "gridPos": { "x": 19, "y": 1, "w": 5, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum(increase(velero_backup_deletion_success_total{schedule!=\"\"}[24h])) / clamp_min(sum(increase(velero_backup_deletion_attempt_total{schedule!=\"\"}[24h])), 1), 1)"
    }
   ]
  },
  {
   "title": "Hours since last Backup",
   "type": "table-old",
   "description": "for schedule backup use only",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 5 },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule!=\"\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup per hour",
   "type": "graph",
   "gridPos": { "x": 0, "y": 11, "w": 24, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_backup_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup success"
    },
    {
     "expr": "round(sum(increase(velero_backup_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup partial failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion success"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion failure"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_total{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items total"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_errors{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items errors_total"
    },
    {
     "expr": "round(sum(increase(velero_backup_validation_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup validation failure"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_warning_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup warning"
    }
   ]
  },
  {
   "title": "Backup time heatmap",
   "type": "heatmap",
   "gridPos": { "x": 0, "y": 19, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\",le!=\"+Inf\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "x": 0, "y": 26, "w": 24, "h": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(velero_backup_tarball_size_bytes{schedule=~\"$schedule\"}[15m]))",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  { "title": "Restore", "type": "row", "gridPos": { "x": 0, "y": 32, "w": 24, "h": 1 } },
  {
   "title": "Restore Total",
   "type": "stat",
   "gridPos": { "x": 0, "y": 33, "w": 4, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_restore_total" }
   ]
  },
  {
   "title": "Restore Success Rate",
   "type": "gauge",
   "gridPos": { "x": 4, "y": 33, "w": 4, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum(increase(velero_restore_success_total[24h])) / clamp_min(sum(increase(velero_restore_attempt_total[24h])), 1), 1)"
    }
   ]
  },
  {
   "title": "Restore per hour",
   "type": "graph",
   "gridPos": { "x": 8, "y": 33, "w": 16, "h": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_restore_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore success"
    },
    {
     "expr": "round(sum(increase(velero_restore_failed_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore failure"
    },
    {
     "expr": "round(sum(increase(velero_restore_validation_failed_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore validation failure"
    },
    {
     "expr": "round(sum(increase(velero_restore_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore partial failure"
    }
   ]
  },
  { "title": "CSI", "type": "row", "gridPos": { "x": 0, "y": 41, "w": 24, "h": 1 } },
  {
   "title": "CSI per hour",
   "type": "graph",
   "gridPos": { "x": 0, "y": 42, "w": 24, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_csi_snapshot_attempt_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot attempt"
    },
    {
     "expr": "round(sum(increase(velero_csi_snapshot_success_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_csi_snapshot_failure_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot failure"
    }
   ]
  }
 ]
}