# Traefik ingress controller
# https://github.com/traefik/traefik-helm-chart

commonLabels:
  estabilis.io/managed-by: platform
  estabilis.io/component: traefik

deployment:
  replicas: 2

tolerations:
  - key: "estabilis.io/workload-type"
    operator: "Equal"
    value: "platform"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: "estabilis.io/pool-type"
              operator: In
              values: ["spot"]
      - weight: 10
        preference:
          matchExpressions:
            - key: "estabilis.io/pool-type"
              operator: In
              values: ["regular"]

service:
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

ports:
  web:
    port: 8000
    exposedPort: 80
  websecure:
    port: 8443
    exposedPort: 443
  metrics:
    port: 9100
    expose:
      default: false
