{{- if .Values.configRepoUrl }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-config-client
  namespace: argocd
  {{- include "estabilis.metadata" . | nindent 2 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: repo-config-client
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: {{ .Values.configRepoUrl | quote }}
        username: x-access-token
        password: |-
          {{`{{ .token }}`}}
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.kvSecrets.configRepoToken | quote }}
{{- end }}
---
{{- if .Values.clientGitopsRepoUrl }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-client-gitops
  namespace: argocd
  {{- include "estabilis.metadata" . | nindent 2 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: repo-client-gitops
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: {{ .Values.clientGitopsRepoUrl | quote }}
        username: x-access-token
        password: |-
          {{`{{ .token }}`}}
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.kvSecrets.clientGitopsRepoToken | quote }}
{{- end }}
