# Azure-specific Velero values

configuration:
  backupStorageLocation:
    - name: default
      provider: azure
      config:
        resourceGroup: ""
        storageAccount: ""
        subscriptionId: ""
        useAAD: "true"
  volumeSnapshotLocation:
    - name: default
      provider: azure
      config:
        resourceGroup: ""
        subscriptionId: ""
        incremental: "true"

initContainers:
  - name: velero-plugin-for-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.14.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

serviceAccount:
  server:
    annotations:
      azure.workload.identity/use: "true"
      azure.workload.identity/client-id: ""  # injected via ArgoCD helm.parameters

podLabels:
  azure.workload.identity/use: "true"
