# Azure-specific Velero values

configuration:
  backupStorageLocation:
    - name: default
      provider: azure
      config:
        useAAD: "true"
  volumeSnapshotLocation:
    - name: default
      provider: azure
      config:
        useAAD: "true"

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

serviceAccount:
  server:
    annotations:
      azure.workload.identity/use: "true"
      azure.workload.identity/client-id: ""  # injected via ArgoCD helm.parameters

podLabels:
  azure.workload.identity/use: "true"
