deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1

singleBinary:
  replicas: 1
  persistence:
    size: 10Gi
  tolerations:
    - key: "estabilis.io/workload-type"
      operator: "Equal"
      value: "platform"
      effect: "NoSchedule"
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: "estabilis.io/pool-type"
                operator: In
                values: ["spot"]
        - weight: 10
          preference:
            matchExpressions:
              - key: "estabilis.io/pool-type"
                operator: In
                values: ["regular"]

minio:
  enabled: false

gateway:
  enabled: false

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
