apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencost-azure-service-key
  namespace: opencost
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: opencost-azure-service-key
    creationPolicy: Owner
    template:
      data:
        service-key.json: |-
          {{`{{ .serviceKey }}`}}
  data:
    - secretKey: serviceKey
      remoteRef:
        key: {{ .Values.kvSecrets.opencostServiceKey | quote }}