commonLabels:
  estabilis.io/managed-by: platform
  estabilis.io/component: kyverno

admissionController:
  replicas: 1
  metricsService:
    create: true

backgroundController:
  enabled: true
  metricsService:
    create: true

cleanupController:
  enabled: true
  metricsService:
    create: true

reportsController:
  enabled: true
  metricsService:
    create: true

grafana:
  enabled: false
