commonLabels:
  estabilis.io/managed-by: platform
  estabilis.io/component: kyverno

admissionController:
  replicas: 1

backgroundController:
  enabled: true

cleanupController:
  enabled: true

reportsController:
  enabled: true

grafana:
  enabled: false
