# OpenCost — Kubernetes cost monitoring
# https://www.opencost.io

opencost:
  exporter:
    cloudProviderApiKey: ""
  carbonCost:
    enabled: true
  prometheus:
    internal:
      enabled: false
    external:
      enabled: true
      url: "http://grafana-mimir-gateway.grafana.svc.cluster.local/prometheus"

tolerations:
  - key: "estabilis.io/workload-type"
    operator: "Equal"
    value: "platform"
    effect: "NoSchedule"

ui:
  enabled: true
