# OpenCost — Kubernetes cost monitoring
# https://www.opencost.io

commonLabels:
  estabilis.io/managed-by: platform
  estabilis.io/component: opencost

opencost:
  exporter:
    cloudProviderApiKey: ""
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
  carbonCost:
    enabled: true
  prometheus:
    internal:
      enabled: false
    external:
      enabled: true
      url: "http://grafana-mimir-gateway.grafana.svc.cluster.local/prometheus"
  ui:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
    securityContext:
      readOnlyRootFilesystem: false

tolerations:
  - key: "estabilis.io/workload-type"
    operator: "Equal"
    value: "platform"
    effect: "NoSchedule"
