# Azure-specific OpenCost values
# Loaded in addition to values.yaml when provider=azure

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
