apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-alerting-rules
  namespace: grafana
  {{- include "estabilis.metadata" . | nindent 2 }}
data:
  {{- if .Values.ruleGroups.platformDown.enabled }}
  tier1-platform-down.yaml: |
{{ .Files.Get "files/tier1-platform-down.yaml" | indent 4 }}
  {{- end }}
  {{- if .Values.ruleGroups.platformDegradation.enabled }}
  tier2-degradation.yaml: |
{{ .Files.Get "files/tier2-degradation.yaml" | indent 4 }}
  {{- end }}
  {{- if .Values.ruleGroups.platformOperational.enabled }}
  tier3-operational.yaml: |
{{ .Files.Get "files/tier3-operational.yaml" | indent 4 }}
  {{- end }}
  {{- range $name, $group := .Values.customRuleGroups }}
  custom-{{ $name }}.yaml: |
    groups:
    - name: {{ $name }}
      interval: 1m
      rules:
      {{- toYaml $group.rules | nindent 6 }}
  {{- end }}
